import "dotenv/config";

export const {
    PORT,
    NODE_ENV,
    MONGO_URI,
    GOOGLE_CLIENT_SECRET,
    WEB_GOOGLE_CLIENT_ID,
    ANDROID_GOOGLE_CLIENT_ID,
    IOS_GOOGLE_CLIENT_ID,
    GOOGLE_REDIRECT_URI: REDIRECT_URI,
    NEWSAPIORG_API_KEY,
    GOOGLE_TRANSLATE_API_KEY,
    GEMINI_API_KEY,
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY,
    COOKIE_PASSWORD,
    RSS_CACHE_DURATION,
    RECOMMENDATION_CACHE_DURATION,
    NEWS_SCRAPING_WINDOW_MS,
    NEWS_SCRAPING_MAX_REQUESTS,
} = process.env;
