import "dotenv/config";

export const {
    PORT,
    MONGO_URI,
    GOOGLE_CLIENT_SECRET,
    WEB_GOOGLE_CLIENT_ID,
    ANDROID_GOOGLE_CLIENT_ID,
    IOS_GOOGLE_CLIENT_ID,
    ACCESS_TOKEN_SECRET,
    ACCESS_TOKEN_EXPIRY,
    REFRESH_TOKEN_SECRET,
    REFRESH_TOKEN_EXPIRY,
    COOKIE_PASSWORD,
    NEWSAPIORG_API_KEY,
    GEMINI_API_KEY
} = process.env;
